
#ifndef LABCAPABILITIESMANAGER_GLOBAL_H
#define LABCAPABILITIESMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LABCAPABILITIESMANAGER_LIBRARY)
#  define LABCAPABILITIESMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define LABCAPABILITIESMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // LABCAPABILITIESMANAGER_GLOBAL_H
